# texlive doesn't compile with clang=11 due to the use of multiple function definitions
c_compiler_version:    # [osx]
- '10'                 # [osx_64]
- '11'                 # [osx_arm64]
cxx_compiler_version:  # [osx]
- '10'                 # [osx_64]
- '11'                 # [osx_arm64]
