{% set version = "20180414" %}

package:
  name: texlive-core
  version: {{ version }}

source:
  url: ftp://tug.org/texlive/historic/2018/texlive-{{ version }}-source.tar.xz
  sha256: fe0036d5f66708ad973cdc4e413c0bb9ee2385224481f7b0fb229700a0891e4e
  patches:
    - 0001-support-poppler-0.64.0.patch

build:
  number: 4
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libxrender-devel') }}  # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
    - {{ cdt('libxau-devel') }}      # [linux]
    - pkg-config
    - texinfo
    - make
    - sed
    - patch
  host:
    - cairo
    - freetype
    - fontconfig
    - gmp
    - harfbuzz >=1.8.*
    - graphite2
    - icu
    - libpng
    - mpfr
    - pixman
    - perl
    - poppler >=0.64.0,<0.66.0
    - zlib
  run:
    - cairo
    - freetype
    - fontconfig
    - gmp
    - harfbuzz >=1.8.*
    - graphite2
    - icu
    - libpng
    - mpfr
    - pixman
    - perl
    - poppler >=0.64.0,<0.66.0
    - zlib

test:
  commands:
    - pdftex --version
    - bibtex --version
    # Test the symlinks.
    - pdflatex --version
    - latex --version

about:
  home: https://www.tug.org/texlive/
  license: GPL-2.0-or-later AND GPL-2.0-only AND GPL-3.0-only AND LPPL-1.3c AND LPPL-1.0 AND Artistic-1.0 AND Apache-2.0 AND MIT AND BSD-3-Clause
  # See https://www.tug.org/texlive/LICENSE.TL
  license_file: LICENSE.TL
  summary: 'An easy way to get up and running with the TeX document production system.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - xhochy
