{% set version = "20170520" %}

package:
  name: texlive-core
  version: {{ version }}

source:
  fn: texlive-{{ version }}-source.tar.xz
  url: https://www.ctan.org/tex-archive/systems/texlive/Source/texlive-{{ version }}-source.tar.xz
  sha256: c0a032aa9fa29e7cb521659779d6415f3b4b062a6a44193fb4e79cfefe7b8954

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
    - cairo 1.14.*
    - gmp 6.1.*
    - icu 58.*
    - mpfr 3.1.*
    - pixman 0.34.*
    - freetype 2.7
    - libpng >=1.6.28,<1.7
    - zlib 1.2.8
    - perl 5.22.2.1
  run:
    - cairo 1.14.*
    - gmp 6.1.*
    - icu 58.*
    - mpfr 3.1.*
    - pixman 0.34.*
    - freetype 2.7
    - libpng >=1.6.28,<1.7
    - zlib 1.2.8
    - perl 5.22.2.1

test:
  commands:
    - pdftex --version
    - bibtex --version
    # Test symlinks to (pdf)latex and try compiling minimal examples.
    - latex --version
    - pdflatex --version 
    - printf '\\documentclass{article}\n\\begin{document}\n\\end{document}\n' | latex
    - printf '\\documentclass{article}\n\\begin{document}\n\\end{document}\n' | pdflatex

about:
  home: https://www.tug.org/texlive/
  license: GPL-2.0+ and GPL-2.0 and GPL-3.0 and LPPL-1.3c and LPPL-1.0 and Artistic-1.0 and Apache-2.0 and MIT and BSD-3-Clause
  summary: 'An easy way to get up and running with the TeX document production system.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
