{% set version = "20180414" %}

package:
  name: texlive-core
  version: {{ version }}

source:
  url: ftp://tug.org/texlive/historic/2018/texlive-{{ version }}-source.tar.xz
  sha256: fe0036d5f66708ad973cdc4e413c0bb9ee2385224481f7b0fb229700a0891e4e
  patches:
      - texlive-20180414-source-upstream_fixes-3.patch

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libxrender-devel') }}  # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
    - {{ cdt('libxau-devel') }}      # [linux]
    - pkg-config
    - texinfo
    - make
    - patch
  host:
    - cairo
    - freetype
    - fontconfig
    - gmp
    - harfbuzz
    - graphite2
    - icu
    - libpng
    - mpfr
    - pixman
    - perl
    - poppler
    - zlib
  run:
    - cairo
    - freetype
    - fontconfig
    - gmp
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - mpfr
    - pixman
    - perl
    - poppler
    - zlib

test:
  commands:
    - pdftex --version
    - bibtex --version
    # Test the symlinks.
    - pdflatex --version
    - latex --version
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.tug.org/texlive/
  license: GPL-2.0+ and GPL-2.0 and GPL-3.0 and LPPL-1.3c and LPPL-1.0 and Artistic-1.0 and Apache-2.0 and MIT and BSD-3-Clause
  summary: 'An easy way to get up and running with the TeX document production system.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
