provider: {linux_ppc64le: default}
travis:
  secure:
    BINSTAR_TOKEN: 4e29HNADS96zGx29+RRe7TuwXBYj2jLmmalYyMhivMhaOHojdhKE89T4USZszXD6/2WmVPzejrqdk1CejxApGl/YuAIAuwchGgGOnc4+jo9bkzU6842QIeOkFvIk7eWSEjEWycEyyT19AOBH+mcOR0eYzyC3lGWNmFpRfMfjImw/27JiOefdjSZkN2a/hyQeXpuZWq3mrKlEe66dIErIpg60fGO1f6/NxoKmfNthvpDMOapzpbucLlREgicYT9peVAIa4LU6mq+lsf3ny+sdTQzpgdL48UUOmAIKD0NOJ69xRgF7nfgGL44pxuHExD5CTD1t+AZucoO30I1eZyts3RUWIWxE5Vpp3Uzl3VTc6e3iEocD9nK0v5FwX3aGJNzv5gi1p9AnOjBwC2oUUyl7KMaUhuh4L0cVoD0Uy1beygXgyJ0iTkvFqslX3w1wUjV2NrEonckyW7fkHsKLHZfgub4GjsGFGcGXgFDX/VCe1QCgmQL8d/065TtPDgxwM/LSu7mTRjbShVb4b2lM01xbH43/mKJ1dAVJ/M9otoW0TvmEx2x5ZheGtuF3VtuQX7M7XpxaQf4KJtQzdoorykJpLqrisb6ICgwDvNIUS6FIKcyr2A00zH3dy3eeZlgWQXRN1o2dtz6D8TsGIekpOmkyww0Btup8wGEQdlEIwKLejqU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
